Metrics Application
jaflih/metrics pull request #24
Opened 2022-03-09 16:49 UTC by jaflih

2022-03-09 18:37 UTC, moise10r requested changes
### Hi @jaflih,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- You have followed  JavaScript best practices. ✔️ 
- The video presenting the features of the project was awesome✔️  
- The app has deployed properly, the home and detail page works as expected :+1: 
- I really like the TDD way you use for writing your test.  keep rocking :rocket: 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 20:35 UTC, jaflih commented on README.md
Ok, thank you. Done.

2022-03-09 20:37 UTC, jaflih commented on src/components/profile.css
> +.company-box {
Thank you.
I update the style.

<img width="251" alt="Capture d’écran 2022-03-09 à 21 27 20" src="https://user-images.githubusercontent.com/7243132/157531473-0fb56dac-18cd-4715-a6d1-d2ac8170ef55.png">
<img width="251" alt="Capture d’écran 2022-03-09 à 21 40 23" src="https://user-images.githubusercontent.com/7243132/157531476-08b23720-4f60-491c-a48c-98fa9cb14289.png">
.

2022-03-09 21:19 UTC, moise10r approved these changes
### Hi @jaflih , 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 21:19 UTC, moise10r commented on src/components/profile.css
> +}
- [ OPTIONAL] I can suggest you remove the `  flex-direction: column;` property so that your image can be positioned to the left in order to follow the [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), see :arrow_down: 


||             ||                ||
|-|----------------------|-| ----------------------|-|
||![go22](https://user-images.githubusercontent.com/57562869/157537439-425e31db-6fd2-499b-bf5b-f77b90e83192.png)|| ![ba22](https://user-images.githubusercontent.com/57562869/157537526-b773d018-845a-4044-8d43-92a771d0d4dc.png) ||

2022-03-10 07:15 UTC, jaflih commented on src/components/profile.css
> +}
@moise10r  
Thank you
![thankyou](https://user-images.githubusercontent.com/7243132/157608606-547b3ff2-d503-49cc-ad66-73fcb52877ba.gif)

2022-03-10 07:15 UTC, merged